server:
  port: 8761
spring:
  application:
    name: microservice-platform-eureka
eureka:
  instance:
    hostname: localhost
  client:
    #是否启用湖区注册服务信息，因为这是一个单节点的EurekaServer，不需要同步其他的EurekaServer节点的数据，所以设置为false；
    fetch-registry: false
    #表示是否向eureka注册服务，即在自己的eureka中注册自己，默认为true，此处应该设置为false；
    register-with-eureka: false
    service-url:
      defaultZone:  http://localhost:8761/eureka